### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [cammac60/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [ ] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
`Make sure the commits are always present tense.`
- [x] I pushed my changes to Github. 

Take a look at the file on: [github](https://github.com/cammac60/mod_0_skills/blob/master/top_down_design.md)  
`It's not formatted using markdown syntax. If you're going to use .md files then the file needs to use markdown syntax. You would have been better served with a .txt file with the current formatting. Please update this file to be more readable, and break down the steps even further adding about 5-10 more sub-steps. Then commit the changes with a properly formatted commit message.`

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 
`We only want one Initial Commit.`

Class #1 Example Object Checklist
- [ ] The object I chose for **Class 1** is an instance of this class. 
`Turing or Galvanize are instances of the coding_school class. Mod-1 would be an instance of a semester, module, or class_level class. Go ahead and update this example object to be an instance of the class you chose.`
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [ ] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 
`Commited with object file`

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 
`Commited with class file`

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready
